FROM tiangolo/uwsgi-nginx-flask:python3.8-alpine
ARG APP=/app
WORKDIR ${APP}

# nickeskov: because pip need to compile dependencies
RUN apk add build-base
COPY requirements.txt ${APP}/requirements.txt
RUN pip3 install -r ${APP}/requirements.txt

COPY . ${APP}
# nickeskov: replace default uwsgi.ini file
COPY uwsgi.ini ${APP}/uwsgi.ini
